config/routes.rb
Rails.application.routes.draw do
  resources :places
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'places#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/place.rb
class Place < ApplicationRecord
  geocoded_by :address
  after_validation :geocode
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  def index
    @places = Place.order('created_at DESC')
  end

  def new
    @place = Place.new
  end

  def create
  @place = Place.new(place_params)
  binding.pry
  if @place.save
    flash[:success] = "Place Added!"
    redirect_to root_path
  else
    render 'new'
  end
  end
  def show 
    @place = Place.find(params[:id])
  end

  def place_params
    params.require(:place).permit(:title,:address,:visited_by)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vagabond</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/places/_form.html.erb
<%= form_for @place do |f| %>
  <fieldset class = "form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </fieldset>

  <fieldset class="form-group">
    <%= f.label :visited_by %>
    <%= f.text_field :visited_by, class: "form-control" %>
  </fieldset>

  <fieldset class="form-group">
    <%= f.label :address, 'Address' %>
    <%= f.text_field :address, class: "form-control" %>
  </fieldset>

  <%= f.submit 'Add!' , class: 'btn btn-primary' %>

<% end %> 

app/views/places/_place.html.erb
<<li>
   <%= link_to place.title, place_path(place) %>

   visited_by <strong> <%= place.visited_by %> </strong>

</li>

app/views/places/create.html.erb
<h1>Places#create</h1>
<p>Find me in app/views/places/create.html.erb</p>

app/views/places/index.html.erb
<header><h1 class="display-4">Places</h1></header>

<%= link_to 'Add place', new_place_path, class: 'btn btn-primary btn-lg' %>

<div class="card">
  <div class="card-block">
    <ul>
      <%= render @places %>
    </ul>
  </div>
</div>

app/views/places/new.html.erb
<header><h1 class="display-4">Add Place</h1></header>

<%= render 'form' %>

app/views/places/show.html.erb
<header><h1 class="display-4"><%= @place.title %></h1></header>

<p>Address: <%= @place.address %></p>
<p>Coordinates: <%= @place.latitude %> <%= @place.longitude %></p>